name: Deploy to Firebase

on:
  push:
    branches:
      - main # Asegúrate de que tu rama principal sea "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout del código
        uses: actions/checkout@v3 # ✅ Corregido

      - name: 🔧 Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 🚀 Deploy a Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
